#!/usr/bin/env bash

debug-emacs() {
    tail -f "$1"
}

usage-msg() {
    printf "%s\n" "debug-emacs <gui|tty>"
}

declare flag="$1"

case "$flag" in
    gui|tty) debug-emacs "$HOME/.emacs.d/emacs-${flag}.log" ;;
          *) usage-msg
esac


