#!/usr/bin/env bash

source $HOME/.bashrc.d/12-emacs.rc

if emacs-dead-p; then
    emacsctl start
fi

input="$@"

if [[ -z "$input" ]]; then
    command emacsclient --create-frame
else
    command emacsclient --create-frame "$input"
fi

