#!/usr/bin/env bash

declare -a input=( $@ )

emacs() {
    source $HOME/.bashrc.d/12-emacs.rc

    local -a params
    local -a finput=( $@ )
    local -a flags=(
	--display="${DISPLAY:-$WAYLAND_DISPLAY}"
	--socket-name="$XDG_RUNTIME_DIR/emacs/server"
    )
    
    emacs-dead-p && emacsctl start
    
    if [[ $TERM == dumb ]]; then
        local is_term_flag+=" --reuse-frame"
    else
        local is_term_flag+=" --tty"
    fi

    if [[ -z $finput ]]; then
	command emacsclient ${flags[@]} $is_term_flag
    else
	command emacsclient ${flags[@]} $is_term_flag ${finput[@]}
    fi
}

emacs "${input[@]}"

