#!/usr/bin/env bash

declare -a input=( $@ )

emacs() {
    source $HOME/.bashrc.d/12-emacs.rc

    local -a params
    local -a finput=( $@ )
    
    emacs-dead-p && emacsctl start

    if [[ $TERM == dumb ]]; then
        params+=" --reuse-frame"
    else
        params+=" --tty"
    fi

    if [[ -z $finput ]]; then
	command emacsclient ${params[@]}
    else
	command emacsclient ${params[@]} ${finput[@]}
    fi
}

emacs "${input[@]}"

