#!/usr/bin/env bash

input="$@"

emacs-lucid() {
    source $HOME/.bashrc.d/12-emacs.rc
    local finput="$@"

    emacs-dead-p && emacsctl start
    
    if [[ -z "$finput" ]]; then
	command emacsclient --reuse-frame
    else
	command emacsclient --reuse-frame "$finput"
    fi    
}

emacs-lucid "$input"

