#!/usr/bin/env bash

read -ra input < <(echo $*)

emacs() {
    source "$HOME/.bashrc.d/12-emacs.rc"

    local is_term_flag
    local -a flags
    read -ra finput < <(echo $*)
    flags=(
	--display="${DISPLAY:-$WAYLAND_DISPLAY}"
	--socket-name="$XDG_RUNTIME_DIR/emacs/server"
    )
    
    emacs-dead-p && emacsctl start

    if [[ $TERM =~ (tmux|xterm)-[0-9].*color ]]; then
        is_term_flag+=" --tty"
    else
        is_term_flag+=" --reuse-frame"
    fi

    
    if [[ -z $finput ]]; then
        command emacsclient ${flags[@]} $is_term_flag
    else
	command emacsclient ${flags[@]} $is_term_flag ${finput[@]}
    fi
}

emacs "${input[@]}"

