#!/usr/bin/env bash

# Workaround to flameshot / xdg-desktop-portal Wayland / D-Bus bug
# - https://github.com/flameshot-org/flameshot/issues/3326
# - https://github.com/flatpak/xdg-desktop-portal/issues/1070

save_dir="$HOME/documents/pictures/Screenshots"

/usr/bin/flameshot ${@:-gui --path $save_dir --clipboard}
