#!/usr/bin/env bash

INPUT="$@"
USER="elijah.beale+root@cloudshare.com"
PASS="epU4MI4ZiW91"
HOST="folders.cloudshare.com"

if [[ -z "$1" ]]; then
    lftp -u "$USER","$PASS" "$HOST"
else
    lftp "$INPUT"
fi

