#!/usr/bin/env -S bash

kill-proc() {
    xargs -I {} kill -9 {}
}

message() {
    echo "Killing ${1}"
}

readarray input <<< $@

for proc_name in ${input[@]}; do
    if [[ "$proc_name" = schildichat* ]]; then
	message "$proc_name"
	kill-proc < <(pgrep -xf "/opt/SchildiChat/schildichat-desktop")
    else
	message "$proc_name"
	kill-proc < <({ pgrep -x "$proc_name" || pgrep -xf "$proc_name" || pgrep "$proc_name"; })
    fi
done
