#!/usr/bin/env bash

input="${1/--/}"

gpu_off='radeon.si_support=1 amdgpu.si_support=0'
gpu_on='radeon.si_support=0 amdgpu.si_support=1'

get-current-gpu() {
    lspci -k | grep -iE 'kernel driver in use: (radeon|amdgpu)' \
	| tr -d ' ' \
	| cut -d ':' -f 2
}

switch-driver() {
    local remove_gpu_commandline="$1"
    local add_gpu_commandline="$2"
    
    sudo grubby \
	 --remove-args="$remove_gpu_commandline" \
	 --args="$add_gpu_commandline" \
	 --update-kernel=ALL

    printf "%s\n" "Will use $(get-current-gpu)"
}

usage() {
    echo "Usage: ${0##*/} [--switch|--current]"
}

case "$input" in
    current)
	get-current-gpu
	;;
    switch)
	if get-current-gpu == 'amdgpu'; then
	    switch-driver "$gpu_on" "$gpu_off"
	else
	    switch-driver "$gpu_off" "$gpu_on"
	fi
	;;
    *)
	usage
esac

