#!/usr/bin/env bash

input="${1/--/}"

get-current-gpu() {
    # if called interactively print the current GPU
    # else only return exit status
    local input="${1/--/}"

    if [[ "$input" = interactive ]]; then
	lspci -k | grep -iE 'k.*e: (radeon|amdgpu)' | tr -d ' ' | cut -d ':' -f 2
    else
	grep -q 'radeon.si_support=1' /etc/default/grub
    fi
}

is-gpu-radeon() {
    get-current-gpu
}

toggle-gpu-on-or-off() {
    confirmation-msg() {
	local dgpu_or_igpu

	is-gpu-radeon && dgpu_or_igpu=iGPU || dgpu_or_igpu=dGPU

	printf "%s\n" "Will use ${dgpu_or_igpu}"
    }

    toggle-dgpu-on() {
	sudo grubby \
	     --remove-args="radeon.si_support=1 amdgpu.si_support=0" \
	     --args="radeon.si_support=0 amdgpu.si_support=1" \
	     --update-kernel=ALL || exit
    }

    toggle-dgpu-off() {
	sudo grubby \
	     --remove-args="radeon.si_support=0 amdgpu.si_support=1" \
	     --args="radeon.si_support=1 amdgpu.si_support=0" \
	     --update-kernel=ALL || exit
    }
    
    if is-gpu-radeon; then
	toggle-dgpu-on
	confirmation-msg
    else
	toggle-dgpu-off
	confirmation-msg
    fi
}

usage-msg() {
    echo "Usage: ${0##*/} [--toggle|--current]"
}

case "$input" in
    current) get-current-gpu --interactive ;;
     toggle) toggle-gpu-on-or-off ;;
          *) usage-msg
esac
