#!/usr/bin/env bash

input="${1/--/}"

get-current-gpu() {
    local input="${1/--/}"

    if [[ "$input" = interactive ]]; then
	lspci -k | grep -iE 'k.*e: (radeon|amdgpu)' | tr -d ' ' | cut -d ':' -f 2
    else
	grep -q 'radeon.si_support=1' /etc/default/grub
    fi
}

toggle-gpu-on-off() {
    local amdgpu_off='radeon.si_support=1 amdgpu.si_support=0'
    local amdgpu_on='radeon.si_support=0 amdgpu.si_support=1'

    @confirmation-msg() {
	local dgpu_or_igpu

	get-current-gpu && dgpu_or_igpu=iGPU || dgpu_or_igpu=dGPU

	printf "%s\n" "Will use ${dgpu_or_igpu}"
    }

    @toggle() {
	sudo grubby --remove-args="$1" --args="$2" --update-kernel=ALL || exit
    }

    if get-current-gpu; then
	@toggle "$amdgpu_off" "$amdgpu_on"
	@confirmation-msg
    else
	@toggle "$amdgpu_on" "$amdgpu_off"
	@confirmation-msg
    fi
}

usage-msg() {
    echo "Usage: ${0##*/} [--toggle|--current]"
}

case "$input" in
    current) get-current-gpu --interactive ;;
     toggle) toggle-gpu-on-off ;;
          *) usage-msg
esac
