#!/usr/bin/env bash

# print connected accesspoint name based on it's radio's MAC address
# If no current accesspoint, print current ethernet device or "unknown"

aps=(
    E8:9F:80:4F:EB:C5 #living room
    E8:9F:80:50:5C:92 #bedroom
    E8:9F:80:DF:DB:2C #office
)

access_point="$(nmcli -f BSSID,ACTIVE dev wifi list | grep yes | cut -d " " -f 1)"
eth_device="$(nmcli -t dev | grep ':ethernet' | grep ':connected:' | cut -d':' -f1)"

print-catch-case() {
    if [[ -n "$eth_device" ]]; then
	printf "$eth_device"
    else
	printf "unknown"
    fi
}

case "$access_point" in
    "${aps[0]}") printf "living-room" ;;
    "${aps[1]}") printf "bedroom"     ;;
    "${aps[2]}") printf "office"      ;;
              *) print-catch-case
esac

	  
