#!/usr/bin/env -S bash -x

##################################################################################
# Launch instances of ungoogled-chromium separated by HOME directories		 #
#										 #
# ungoogled-chromium <home-dir-name|cloudshare|incognito> <args>		 #
#										 #
# must be called with a DIRECTORY name as the first argument, but will		 #
# treat any first argument as a directory name so be careful. Upon launch	 #
# proceeds with these steps:							 #
#										 #
# 1. checks if the directory is called 'temp', and sets the $home var based on	 #
#    this									 #
# 2. checks if the home directory exists, creating it if it doesn't		 #
# 3a. based on the home directory name, calls ungoogled-chromium with a		 #
#     home directory in either the PARENT directory, under a SUB directory, or	 #
#     in /tmp with a unique name						 #
# 3b. if 'incognito' is passed as the name, launches ungoogled-chromium with the #
#     --incognito flag								 #
##################################################################################
ungoogled-chromium() {
    set -x
    local input=( $@ )
    local sdir=${input[0]}
    local args=( ${input[@]:1:${#input[@]}} )
    local pdir="$HOME/.ungoogled-chromium"
    local tdir="ungoogled-chromium-${sdir}"
    local home
    local flatpak="$(flatpak list --columns=application | grep -iE '^.*ungoogled.?chromium$')"

    if [[ "$sdir" == unsafe ]]; then
	local downloads="$pdir/$sdir/.ungoogled-chromium-downloads"
    else
	local downloads="$HOME/downloads"
    fi

    # limit the $PATH so we don't call this wrapper, and get path to binary
    local rpm="PATH='/usr/bin:/usr/local/bin' $(which ungoogled-chromium)"

    # chrome flags and switches
    # see:
    #  - https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/flag_descriptions.cc
    #  - https://github.com/ungoogled-software/ungoogled-chromium/blob/master/docs/flags.md

    if [[ "$sdir" == unsafe ]]; then
	local enable_flag_privacy=(
	    'FingerprintingCanvasImageDataNoise,'
	    'FingerprintingCanvasMeasuretextNoise,'
	    'FingerprintingClientRectsNoise,'
	    'ForcePunycodeHostnames,'
	    'DisableGreaseTLS,'
	    'HttpAcceptHeader,'
	    'NoPings,'
	    'ReducedSystemInfo,'
	    'RemoveClientHints,'
	)
    elif [[ "$sdir" == dmz ]]; then
	unset -v enable_flag_privacy
    else	
	local enable_flag_privacy=(
	    'FingerprintingCanvasImageDataNoise,'
	    'FingerprintingCanvasMeasuretextNoise,'
	    'FingerprintingClientRectsNoise,'
	    'ForcePunycodeHostnames,'
	    'DisableGreaseTLS,'
	    'HttpAcceptHeader,'
	    'NoPings,'
	    'NoCrossOriginReferrers,'
	    'ReducedSystemInfo,'
	    'RemoveClientHints,'
	)
    fi


    local enable_flag_privacy_experimental=(
	'PartitionedCookies,'
	'ThirdPartyStoragePartitioning,'
	'SplitCacheByNetworkIsolationKey,'
    )

    local disable_flags=(
	'DesktopPWAsRunOnOsLogin,'
	'WebAssemblyTrapHandler,'
    )

    # can't use VAAPI with AMDGPU due to AMD JPEG image decode acceleration
    # returning multiple buffer objects when chrome only supports one
    #
    # see: https://issues.chromium.org/issues/40632250
    #      https://bbs.archlinux.org/viewtopic.php?pid=2080653#p2080653
    #      https://gist.github.com/thubble/235806c4c64b159653de879173d24d9f/
    if lspci -k | grep -qiE 'kernel driver in use: (radeon|amdgpu)'; then
	local switches=(
	    --disable-features="$(printf "%s" "${disable_flags[@]}" $'\n')"
	    --enable-features="$(printf "%s" "${enable_flag_privacy[@]}${enable_flag_privacy_experimental[@]}" $'\n')"
	    --omnibox-autocomplete-filtering=search-bookmarks-chrome
	    --omnibox-autocomplete-filtering=search-bookmarks-chrome
	    --extension-mime-request-handling=always-prompt-for-install
	    --disable-search-engine-collection
	)
    else
	local enable_flag_gpu=(
	    'IgnoreGpuBlockList,'
	    'ZeroCopy,'
	)

	local enable_flag_gpu_extra=(
	    'RawDraw,'
	    'GpuRasterization,'
	    'CanvasOopRasterization,'
	    'Accelerated2dCanvas,'
	    'UIEnableSharedImageCacheForGpu,'
	    'UseGpuSchedulerDfs,'
	    'EnableDrDc,'
	    'ClientGmbInterface,'
	    'Vp9kSVCHWDecoding,'
	    'VaapiJpegImageDecodeAcceleration,'
	    'VaapiWebPImageDecodeAcceleration,'
	    'GainmapHdrImages,'
	    'EnablePixelCanvasRecording,'
	    'AcceleratedVideoDecodeLinuxGL,'
	    'AcceleratedVideoEncoder,'
	    'VaapiVideoEncoder,'
	    'VaapiVideoDecoder,'
	    'VaapiIgnoreDriverChecks,'
	)

	local switches=(
	    --disable-features="$(printf "%s" "${disable_flags[@]}" $'\n')"
	    --enable-features="$(printf "%s" "${enable_flag_gpu[@]}${enable_flag_gpu_extra[@]}${enable_flag_privacy[@]}${enable_flag_privacy_experimental[@]}" $'\n')"
	    --omnibox-autocomplete-filtering=search-bookmarks-chrome
	    --extension-mime-request-handling=always-prompt-for-install
	    --disable-search-engine-collection
	    --disable-gpu-driver-bug-workarounds
	)
    fi

    _set-home() {
	set -x
	case "$sdir" in
	    incognito|temp)
		home="/tmp/${tdir}-$(openssl rand -hex 16)" ;;
	    *)
		home="${pdir}/${sdir}"
	esac
	set +x
    }

    _populate-home() {
	set -x
	if [[ ! -d "$home" ]] && [[ -e "${pdir}/template-${sdir}" ]]; then
	    cp -a "${pdir}/template-${sdir}" "$home"
	fi
	set +x
    }

    _create-download-dir() {
	if [[ ! -d "$downloads" ]]; then
	    mkdir -p "$downloads"
	fi
    }

    _ungoogled-chromium() {
	set -x
	local input=( $@ )
	if [[ -n "$flatpak" ]]; then
	    env HOME="$home" flatpak run \
		--filesystem="$downloads" \
		"$flatpak" \
		"${switches[@]}" \
		"${input[@]}"
	else
	    # what args need to be here to have distinct working directories?
	    "$rpm" "${input[@]}"
	fi
	set +x
    }

    _run-chromium() {
	set -x
	_set-home
	_populate-home
	_create-download-dir
	case "$sdir" in
	    incognito|dmz)
		_ungoogled-chromium --incognito ${args[@]} ;;
	    work|personal|unsafe)
		_ungoogled-chromium ${args[@]} ;;
	    *)
		echo "Not a valid profile!" && exit 1
	esac
	set +x
    }

    _run-chromium
    set +x
}

input=( $@ )
ungoogled-chromium ${input[@]}

